"""QSOL-IBAE deterministic execution kernel."""

from ._records import MAX_IDENTITY_INTEGER_BITS, MAX_RECORD_TEXT_BYTES
from .canonical import (
    canonical_fingerprint,
    canonical_json,
    canonical_tool_key,
    domain_fingerprint,
)
from .epistemic import (
    EpistemicClass,
    EpistemicRecord,
    EpistemicState,
    ObservationProvenance,
)
from .executor import BudgetExceeded, InvariantExecutor
from .invariants import BudgetLimits, detect_short_cycle
from .obligations import (
    Obligation,
    ObligationReadiness,
    ObligationRegistry,
    ObligationStatus,
    canonical_obligation_id,
)
from .orchestration import (
    AGENT_PROTOCOL,
    CAPABILITY_ARGUMENT_SCHEMA,
    LOGICAL_CLOCK_PROFILE,
    MAX_PROPOSALS_PER_BATCH,
    STRATEGY_PARAMETER_SCHEMA,
    ActionProposal,
    AdmissionDecision,
    AdmissionReceipt,
    AdmissionTransition,
    AuthorityLayer,
    BatchRejection,
    BatchStatus,
    Capability,
    DecisionStatus,
    OccurrenceOwnership,
    OrchestrationLimits,
    OrchestrationState,
    ProposalBatch,
    ProposalOrdering,
    RecoveryAction,
    RejectionReason,
    ReplaySafety,
    Strategy,
    StrategyParameterSpec,
    StrategySchema,
    StrategyValueKind,
    admit_batch,
)
from .policy import PolicyViolation, require_openai_remote_provider
from .runtime import (
    RUNTIME_PROTOCOL_VERSION,
    RuntimeLimits,
    RuntimeReceipt,
    RuntimeRejected,
    RuntimeSnapshot,
    RuntimeTransition,
    RustRuntimeSession,
    rust_canonical_json,
)

__all__ = [
    "AGENT_PROTOCOL",
    "CAPABILITY_ARGUMENT_SCHEMA",
    "LOGICAL_CLOCK_PROFILE",
    "MAX_IDENTITY_INTEGER_BITS",
    "MAX_PROPOSALS_PER_BATCH",
    "MAX_RECORD_TEXT_BYTES",
    "STRATEGY_PARAMETER_SCHEMA",
    "ActionProposal",
    "AdmissionDecision",
    "AdmissionReceipt",
    "AdmissionTransition",
    "AuthorityLayer",
    "BatchRejection",
    "BatchStatus",
    "BudgetExceeded",
    "BudgetLimits",
    "Capability",
    "DecisionStatus",
    "EpistemicClass",
    "EpistemicRecord",
    "EpistemicState",
    "InvariantExecutor",
    "Obligation",
    "ObligationReadiness",
    "ObligationRegistry",
    "ObligationStatus",
    "ObservationProvenance",
    "OccurrenceOwnership",
    "OrchestrationLimits",
    "OrchestrationState",
    "PolicyViolation",
    "ProposalBatch",
    "ProposalOrdering",
    "RecoveryAction",
    "RejectionReason",
    "ReplaySafety",
    "RUNTIME_PROTOCOL_VERSION",
    "RuntimeLimits",
    "RuntimeReceipt",
    "RuntimeRejected",
    "RuntimeSnapshot",
    "RuntimeTransition",
    "RustRuntimeSession",
    "Strategy",
    "StrategyParameterSpec",
    "StrategySchema",
    "StrategyValueKind",
    "admit_batch",
    "canonical_fingerprint",
    "canonical_json",
    "canonical_obligation_id",
    "canonical_tool_key",
    "detect_short_cycle",
    "domain_fingerprint",
    "require_openai_remote_provider",
    "rust_canonical_json",
]
